site_name: ROS 2 筆記
site_description: 正體中文 ROS 2 相關教學文件，包含 DDS、Zenoh 及 Autoware 等內容
site_author: ChenYing Kuo
site_url: https://ros2.tw

theme:
  name: material
  # Able to adjust the color mode
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切換到深色模式
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切換到淺色模式

markdown_extensions:
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  # Admonition support
  - admonition

extra:
  # Google Analytics
  analytics:
    provider: google
    property: G-J7VWGLN65L

nav:
  - '簡介': 'index.md'
  - 'ROS 2 入門':
    - 'ROS 2 介紹': 'ros2/introduction.md'
    - 'ROS 2 安裝': 'ros2/installation.md'
  - 'ROS 2 實戰':
    - 'ROS 2 指令': 'ros2/command.md'
    - 'ROS 2 通訊方式': 'ros2/communication.md'
    - 'ROS 2 編譯': 'ros2/building.md'
    - 'ROS 2 QoS': 'ros2/qos.md'
    - 'ROS 2 錄製與重放': 'ros2/record.md'
    - 'ROS 2 好用工具': 'ros2/tools.md'
    - 'ROS 2 小技巧': 'ros2/tips.md'
    - 'SROS': 'ros2/sros.md'
  - 'ROS 2 通訊層':
    - 'rmw_cyclonedds 介紹': 'ros2/rmw_cyclonedds.md'
    - 'rmw_zenoh 基本介紹': 'ros2/rmw_zenoh/basic.md'
    - 'rmw_zenoh 進階介紹': 'ros2/rmw_zenoh/advanced.md'
    - 'rmw_zenoh 實戰': 'ros2/rmw_zenoh/hands_on.md'
  - 'DDS 入門':
    - 'DDS 介紹': 'dds/introduction.md'
  - 'Zenoh 入門':
    - 'Zenoh 介紹': 'zenoh/introduction.md'
    - 'Zenoh 模式': 'zenoh/mode.md'
    - 'Zenoh key': 'zenoh/keyexpr.md'
    - 'Zenoh 共享記憶體': 'zenoh/shared_memory.md'
    - 'Zenoh debug 方法': 'zenoh/debug.md'
    - 'zenoh-bridge-ros2dds': 'zenoh/zenoh_bridge_ros2.md'
  - 'Autoware 入門':
    - 'Autoware 介紹': 'autoware/introduction.md'
    - 'Autoware 安裝': 'autoware/installation.md'
    - 'Autoware 模組': 'autoware/modules.md'
    - 'Autoware 地圖': 'autoware/map.md'
    - 'Autoware 模擬': 'autoware/simulation.md'
    - 'Autoware API': 'autoware/api.md'
  - 'AGL 入門':
    - 'AGL 介紹': 'agl/introduction.md'
    - 'AGL 安裝': 'agl/installation.md'
